services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway-sga-transportes:
    build: ./client-gateway-sga-transportes
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway-sga-transportes/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  customers-ms:
    build: ./customers-ms
    volumes:
      - ./customers-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${CUSTOMERS_DATABASE_URL}
#  customers-db:
#    container_name: customers-database
#    image: postgres:17.7
#    restart: always
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=${ORDERS_DB_PASSWORD}
#      - POSTGRES_DB=customersdb